/**
 * CreationPipeline — 4-step serial pipeline for novel creation.
 *
 * Step order: foundation → architecture → characters → outline
 * Each step receives the full context of all previous steps as structured summary.
 * No mesh calls — each step only depends on previous outputs.
 *
 * Can be called individually (advanced mode) or chained via runFullPipeline() (fast mode).
 */
import { getPrisma } from "../../../platform/db/client";
import { createNovelRepo } from "../../../platform/data/repositories/novelRepository";
import { createReferenceBookRepo } from "../../../platform/data/repositories/referenceBookRepository";
import type { GoldenFingerData, LoopSkeletonData } from "../../../platform/data/repositories/novelRepository";
import { serializeTags } from "../../../platform/data/tagHelpers";

// ── Step dependencies ──
import { generateStoryCore, getStoryCore, type StoryCoreResult } from "./storyCoreService";
// bookFraming removed — framing fields now generated by unified story-core prompt (step1)
import {
  generateCharacters,
  persistCharacters,
} from "./characterPrep/characterService";
import {
  getArchitectureTemplate,
  buildExpectationProfile,
  listArchitectureTemplates,
} from "./architectureEngine/architectureRegistry";
import {
  generateLoopSkeleton,
  expandLoopToVolume,
  computeLoopCount,
} from "./architectureEngine/loopTemplateService";
import type {
  ArchitectureType,
  LoopSkeleton,
  ExpandedVolume,
} from "./architectureEngine/types";
import {
  updateStepState,
  getPipelineState,
  createInitialPipelineState,
  type PipelineState,
  type StepName,
} from "./pipelineState";

// ─── Types ─────────────────────────────────────────────

export interface PipelineProgress {
  step: string;
  detail: string;
  percent: number; // 0-100
}

export type ProgressCallback = (progress: PipelineProgress) => void;

export interface ReferenceAnalysisResult {
  detectedArchitecture: { type: ArchitectureType; confidence: number } | null;
  loopStats: { totalLoops: number; avgChaptersPerLoop: number | null } | null;
  coolPointDensity: Array<{ chapterIndex: number; level: string }>;
  hookPatterns: Record<string, number> | null; // 钩子类型 → 占比
  goldenFingerBounds: { abilities: string[]; limits: string[] } | null;
  settingTimeline: Array<{ chapterIndex: number; settingName: string }>;
}

export interface ArchConfirmationResult {
  loopSkeleton: LoopSkeleton | null; // nullable — skeleton moved to Step 4 (outline)
  goldenFinger: { abilities: string[]; limits: string[] };
  centralQuestion: string;
  endingDirection: string;
}

export interface CharacterConfigResult {
  characterCount: number;
  characters: Array<{ name: string; role: string; loopFunctionTag: string | null }>;
}

// ─── Pipeline Class ────────────────────────────────────

export class CreationPipeline {
  private novelId: string;

  constructor(novelId: string) {
    this.novelId = novelId;
  }

  /**
   * Build a structured summary of all completed previous steps' outputs.
   * Each subsequent AI call receives this as context, ensuring a serial pipeline
   * where every step benefits from richer upstream context.
   */
  private async buildSerialContext(upToStep: string): Promise<string> {
    const prisma = getPrisma();
    const novelRepo = createNovelRepo(prisma);
    const novel = await prisma.novel.findUnique({
      where: { id: this.novelId },
      select: {
        storySummary: true, centralQuestion: true, endingDirection: true,
        genre: true, narrativePov: true, pacePreference: true,
        tonePitch: true, emotionIntensity: true,
        targetAudience: true, bookSellingPoint: true, commercialTags: true,
        competingFeel: true, first30ChapterPromise: true,
        architectureType: true,
      },
    });
    if (!novel) return "";

    const parts: string[] = ["[前序步骤上下文 — 串行流水线自动注入]"];
    const { parseTags } = await import("../../../platform/data/tagHelpers");

    // Step 1 foundation context
    if (novel.storySummary) {
      parts.push(`## 故事核心\n简介：${novel.storySummary}\n核心悬念：${novel.centralQuestion ?? ""}\n结局方向：${novel.endingDirection ?? ""}`);
    }
    const gf = await novelRepo.getGoldenFinger(this.novelId);
    if (gf) {
      parts.push(`## 金手指\n名称：${gf.goldenFingerName}\n能力：${gf.abilities.join("；")}\n限制：${gf.limits.join("；")}`);
    }
    if (novel.targetAudience || novel.bookSellingPoint) {
      parts.push(`## 商业定位\n目标读者：${novel.targetAudience ?? ""}\n核心卖点：${novel.bookSellingPoint ?? ""}\n前30章承诺：${novel.first30ChapterPromise ?? ""}`);
    }

    // Step 2 architecture context (includes reference book analysis when available)
    if (upToStep === "architecture" || upToStep === "characters" || upToStep === "outline") {
      if (novel.architectureType) parts.push(`## 架构选择\n类型：${novel.architectureType}`);
      const ep = await novelRepo.getExpectationProfile(this.novelId);
      if (ep) parts.push(`## 期待参数\n${JSON.stringify(ep)}`);

      // Inject reference book setting timeline for world-building guidance
      try {
        const refBookRepo = createReferenceBookRepo(prisma);
        const annotations = await refBookRepo.getAnnotations(this.novelId);
        const keySettings = (annotations as any)?.keySettings as Array<{ chapterIndex: number; settingName: string; description: string }> | undefined;
        if (keySettings?.length) {
          const settingSummary = keySettings
            .sort((a, b) => a.chapterIndex - b.chapterIndex)
            .map(s => `第${s.chapterIndex}章：${s.settingName} — ${s.description ?? ""}`)
            .slice(0, 15)
            .join("\n");
          parts.push(`## 参考书设定时间线\n${settingSummary}`);
        }
      } catch { /* best-effort */ }
    }

    // Step 3 characters context
    if (upToStep === "characters" || upToStep === "outline") {
      const chars = await prisma.novelCharacter.findMany({
        where: { novelId: this.novelId },
        select: { name: true, role: true, personality: true, factionLabel: true },
      });
      if (chars.length > 0) {
        const charList = chars.map(c => `- ${c.name}（${c.role === "protagonist" ? "主角" : c.role === "antagonist" ? "对手" : "配角"}）：${c.personality ?? ""}${c.factionLabel ? ` [${c.factionLabel}]` : ""}`).join("\n");
        parts.push(`## 角色阵容\n${charList}`);
      }
    }

    return parts.join("\n\n");
  }

  // ── runFoundation: Story Core ────────────────────────

  async runFoundation(onProgress?: ProgressCallback): Promise<StoryCoreResult> {
    await updateStepState(this.novelId, "foundation", { status: "generating" });
    onProgress?.({ step: "story_core", detail: "正在生成故事核心...", percent: 5 });

    const novelRepo = createNovelRepo(getPrisma());
    const novel = await novelRepo.findStoryCore(this.novelId);

    let result: StoryCoreResult;
    if (novel?.storySummary) {
      const existing = await getStoryCore(this.novelId);
      result = {
        storySummary: existing?.storySummary ?? "",
        centralQuestion: existing?.centralQuestion ?? "",
        endingDirection: existing?.endingDirection ?? "",
        genre: null,
        narrativePov: null,
        pacePreference: null,
        tonePitch: null,
        emotionIntensity: null,
        targetAudience: null,
        commercialTags: null,
        competingFeel: null,
        bookSellingPoint: null,
        first30ChapterPromise: null,
      };
    } else {
      result = await generateStoryCore(this.novelId);
    }

    await updateStepState(this.novelId, "foundation", {
      status: "completed",
      result,
    });
    return result;
  }

  // ── analyzeReferenceBook (private): Reference Book Analysis ─

  private async analyzeReferenceBook(
    onProgress?: ProgressCallback,
  ): Promise<ReferenceAnalysisResult | null> {
    await updateStepState(this.novelId, "architecture", { status: "generating" });
    onProgress?.({ step: "architecture", detail: "正在分析参考书...", percent: 15 });

    const refBookRepo = createReferenceBookRepo(getPrisma());
    const rb = await refBookRepo.findByNovel(this.novelId);

    if (!rb?.content) {
      await updateStepState(this.novelId, "architecture", { status: "skipped", result: null });
      return null;
    }

    const annotations = await refBookRepo.getAnnotations(this.novelId) ?? {};
    const analysisSummary = await refBookRepo.getAnalysisSummary(this.novelId);

    const result: ReferenceAnalysisResult = {
      detectedArchitecture: analysisSummary?.detectedArchitecture
        ? { type: analysisSummary.detectedArchitecture.type as ArchitectureType, confidence: analysisSummary.detectedArchitecture.confidence }
        : null,
      loopStats: analysisSummary?.loopStats ?? null,
      coolPointDensity: (annotations as any)?.coolPointDensity ?? [],
      hookPatterns: (annotations as any)?.hookPatterns ?? null,
      goldenFingerBounds: (annotations as any)?.goldenFingerBounds ?? null,
      settingTimeline: (annotations as any)?.settingTimeline ?? [],
    };

    await updateStepState(this.novelId, "architecture", { status: "completed", result });
    return result;
  }

  // ── runArchitecture: Architecture & Loop Skeleton ────

  async runArchitecture(
    params: {
      goldenFinger?: { abilities: string[]; limits: string[] };
      centralQuestion?: string;
      endingDirection?: string;
    },
    onProgress?: ProgressCallback,
  ): Promise<ArchConfirmationResult> {
    // Run reference book analysis for auto-configuration data
    await this.analyzeReferenceBook(onProgress);

    await updateStepState(this.novelId, "architecture", { status: "generating" });
    onProgress?.({ step: "architecture", detail: "正在读取参考书分析...", percent: 22 });

    const prisma = getPrisma();
    const novel = await prisma.novel.findUnique({
      where: { id: this.novelId },
      select: { description: true },
    });

    // Auto-fill golden finger from reference book analysis
    const refBookRepo = createReferenceBookRepo(prisma);
    const refAnnotations = await refBookRepo.getAnnotations(this.novelId);
    let goldenFinger = params.goldenFinger ?? { abilities: [], limits: [] };
    if (!params.goldenFinger && refAnnotations?.goldenFingerBounds) {
      const bounds = refAnnotations.goldenFingerBounds as { abilities: string[]; limits: string[] };
      if (bounds.abilities?.length > 0 || bounds.limits?.length > 0) {
        goldenFinger = bounds;
      }
    }

    const novelRepo = createNovelRepo(prisma);
    await novelRepo.setGoldenFinger(this.novelId, goldenFinger);

    await prisma.novel.update({
      where: { id: this.novelId },
      data: {
        centralQuestion: params.centralQuestion ?? novel?.description ?? undefined,
        endingDirection: params.endingDirection ?? undefined,
      },
    });

    // Loop skeleton moved to Step 4 (outline) — generated with full context
    const result: ArchConfirmationResult = {
      loopSkeleton: null,
      goldenFinger,
      centralQuestion: params.centralQuestion ?? "",
      endingDirection: params.endingDirection ?? "",
    };

    await updateStepState(this.novelId, "architecture", {
      status: "completed",
      result,
    });
    return result;
  }

  // ── runCharacters: Character Generation ──────────────

  async runCharacters(
    onProgress?: ProgressCallback,
  ): Promise<CharacterConfigResult> {
    await updateStepState(this.novelId, "characters", { status: "generating" });
    onProgress?.({ step: "characters", detail: "正在配置角色...", percent: 45 });

    const prisma = getPrisma();
    const charCount = await prisma.novelCharacter.count({
      where: { novelId: this.novelId },
    });

    if (charCount === 0) {
      const chars = await generateCharacters(this.novelId);
      await persistCharacters(this.novelId, chars);
    }

    const characters = await prisma.novelCharacter.findMany({
      where: { novelId: this.novelId },
      select: { name: true, role: true, loopFunctionTag: true },
    });

    const result: CharacterConfigResult = {
      characterCount: characters.length,
      characters: characters.map((c) => ({
        name: c.name,
        role: c.role,
        loopFunctionTag: c.loopFunctionTag,
      })),
    };

    await updateStepState(this.novelId, "characters", {
      status: "completed",
      result,
    });
    return result;
  }

  // ── generateLoopSkeleton: Create Loop Skeleton ───────

  async generateLoopSkeleton(
    onProgress?: ProgressCallback,
  ): Promise<LoopSkeleton> {
    onProgress?.({ step: "skeleton", detail: "正在生成回环骨架...", percent: 55 });

    const prisma = getPrisma();
    const novelRepo = createNovelRepo(prisma);
    const novel = await prisma.novel.findUnique({
      where: { id: this.novelId },
      select: { architectureType: true, estimatedChapterCount: true },
    });

    // Return existing skeleton if present (via typed accessor)
    const existing = await novelRepo.getLoopSkeleton(this.novelId);
    if (existing && existing.loops?.length > 0) {
      return existing as unknown as LoopSkeleton;
    }

    const archType = (novel?.architectureType as ArchitectureType) ?? "case_driven";
    const estCh = novel?.estimatedChapterCount ?? 500;
    const loopCount = computeLoopCount(estCh);

    const skeleton = await generateLoopSkeleton({
      novelId: this.novelId,
      architectureType: archType,
      totalLoops: loopCount,
    });

    await novelRepo.setLoopSkeleton(this.novelId, skeleton as unknown as LoopSkeletonData);

    return skeleton;
  }

  // ── expandVolume: Expand a Single Volume ─────────────

  async expandVolume(
    volumeOrder: number,
    onProgress?: ProgressCallback,
  ): Promise<ExpandedVolume> {
    onProgress?.({
      step: "expand_volume",
      detail: `正在展开第${volumeOrder}卷...`,
      percent: 55 + volumeOrder * 5,
    });

    const prisma = getPrisma();
    const novelRepo = createNovelRepo(prisma);
    const skeletonData = await novelRepo.getLoopSkeleton(this.novelId);
    if (!skeletonData) {
      throw new Error("No loop skeleton found. Generate skeleton first.");
    }
    const skeleton = skeletonData as unknown as LoopSkeleton;

    // Get previous volume summaries for context
    const previousVolumes = await prisma.volume.findMany({
      where: { novelId: this.novelId, sortOrder: { lt: volumeOrder } },
      orderBy: { sortOrder: "asc" },
      select: { summary: true },
    });
    const previousSummaries = previousVolumes
      .map((v) => v.summary)
      .filter(Boolean) as string[];

    const expanded = await expandLoopToVolume(
      this.novelId,
      volumeOrder,
      skeleton,
      previousSummaries,
    );

    // Persist to DB
    const existingVol = await prisma.volume.findFirst({
      where: { novelId: this.novelId, sortOrder: volumeOrder },
    });

    const volumeId = existingVol
      ? (
          await prisma.volume.update({
            where: { id: existingVol.id },
            data: { title: expanded.title, summary: expanded.summary },
          })
        ).id
      : (
          await prisma.volume.create({
            data: {
              novelId: this.novelId,
              sortOrder: volumeOrder,
              title: expanded.title,
              summary: expanded.summary,
            },
          })
        ).id;

    let globalOrder = await prisma.chapter.count({
      where: { novelId: this.novelId },
    });

    for (const ch of expanded.phases.flatMap((p) => p.chapters)) {
      globalOrder++;
      const vcp = await prisma.volumeChapterPlan.findFirst({
        where: { volumeId, chapterOrder: ch.chapterOrder },
      });

      const planData = {
        title: ch.title,
        summary: ch.summary,
        purpose: ch.expectation,
        exclusiveEvent: ch.coreEvent,
        endingState: ch.endingHook,
        loopPhase: ch.loopPhase,
        loopIndex: volumeOrder,
        coolPointType: ch.coolPointType,
        hookType: ch.hookType,
        chapterType: ch.chapterType,
      };

      if (vcp) {
        await prisma.volumeChapterPlan.update({
          where: { id: vcp.id },
          data: planData,
        });
        if (vcp.chapterId) {
          await prisma.chapter.update({
            where: { id: vcp.chapterId },
            data: {
              title: ch.title,
              order: globalOrder,
              expectation: ch.expectation,
            },
          });
        }
      } else {
        const chapter = await prisma.chapter.create({
          data: {
            novelId: this.novelId,
            order: globalOrder,
            title: ch.title,
            expectation: ch.expectation,
            chapterStatus: "planned",
          },
        });
        await prisma.volumeChapterPlan.create({
          data: { ...planData, volumeId, chapterOrder: ch.chapterOrder, chapterId: chapter.id },
        });
      }
    }

    return expanded;
  }

  // ── runOutline: Full Blueprint (all volumes) ─────────

  async runOutline(
    mode: "full" | "per_volume" = "full",
    onProgress?: ProgressCallback,
  ): Promise<{ skeleton: LoopSkeleton; expandedVolumes: number }> {
    await updateStepState(this.novelId, "outline", { status: "generating" });

    const skeleton = await this.generateLoopSkeleton(onProgress);
    let expandedCount = 0;

    if (mode === "full") {
      for (let i = 0; i < skeleton.loops.length; i++) {
        onProgress?.({
          step: "outline",
          detail: `正在展开第 ${i + 1}/${skeleton.totalLoops} 卷...`,
          percent: 55 + Math.round(((i + 1) / skeleton.totalLoops) * 30),
        });
        await this.expandVolume(i + 1);
        expandedCount++;
      }

      // Enter writing mode when all volumes are generated
      onProgress?.({ step: "outline", detail: "正在启动写作模式...", percent: 92 });
      const novelRepo = createNovelRepo(getPrisma());
      const status = await novelRepo.findStatus(this.novelId);
      if (status?.projectStatus !== "in_progress") {
        await novelRepo.update(this.novelId, { projectStatus: "in_progress" });
      }
    }

    const result = { skeleton, expandedVolumes: expandedCount };
    await updateStepState(this.novelId, "outline", {
      status: "completed",
      result,
    });
    return result;
  }

}
